version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: django
      versions: [">=3.0", "<4.2"]
    # ignore all boto3 and botocore patch updates
    - dependency-name: boto3
      update-types: ["version-update:semver-patch"]
    - dependency-name: botocore
      update-types: ["version-update:semver-patch"]
