# Generated by Django 4.2.20 on 2025-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0008_alter_feedback_found_useful_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="vote",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MORE_LIKELY", "More likely"),
                    ("LESS_LIKELY", "Less likely"),
                    ("NO_DIFFERENCE", "No change"),
                ],
                max_length=100,
            ),
        ),
    ]
