# Generated by Django 4.2.20 on 2025-08-28 10:19

import django_extensions.db.fields
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0009_alter_feedback_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoElectionFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("no_election_feedback_text", models.TextField(blank=True)),
                (
                    "source_url",
                    models.CharField(
                        blank=True,
                        default="https://whocanivotefor.co.uk",
                        max_length=800,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        default=feedback.models.generate_feedback_token,
                        max_length=100,
                    ),
                ),
                ("flagged_as_spam", models.BooleanField(default=False)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
