# Generated by Django 4.2.20 on 2025-08-28 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0010_noelectionfeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noelectionfeedback",
            options={
                "verbose_name": "No Election Page Feedback",
                "verbose_name_plural": "No Election Page Feedback",
            },
        ),
    ]
