# Generated by Django 4.2.18 on 2025-03-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0022_nationalparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="localparty",
            name="bluesky",
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="localparty",
            name="instagram",
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
