# Generated by Django 5.2.12 on 2026-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0023_localparty_bluesky_localparty_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyemblem",
            name="description",
            field=models.CharField(max_length=300),
        ),
    ]
