# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0024_alter_partyemblem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="ec_id",
            field=models.CharField(
                db_index=True,
                help_text="\n            An ID issued by The Electoral Commission in their party register,\n            with the exception of Democracy Club pseudo IDs for special parties\n        ",
                max_length=25,
                null=True,
                unique=True,
                verbose_name="Electoral Commission Identifier",
            ),
        ),
    ]
