repos:
-   repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
    - id: djhtml
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.4.6'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --extend-exclude, TCH]
    - id: ruff-format
