AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda

  WCIVF Template for aws-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters:

  AppDjangoSettingsModule:
    Description: "The DJANGO_SETTINGS_MODULE environment variable passed to the app."
    Type: String

  AppDBHost:
    Description: "The DB_HOST environment variable passed to the app."
    Type: String

  AppDBPassword:
    Description: "The DB_PASSWORD environment variable passed to the app."
    Type: String

  AppSentryDsn:
    Description: "The SENTRY_DSN environment variable passed to the app."
    Type: String

Resources:
  WCIVFControllerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: WCIVFControllerFunction
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/WCIVFLambdaExecutionRole"
      CodeUri: .
      Handler: wcivf.lambda_handler.handler
      Runtime: python3.6
      Environment:
        Variables:
          DJANGO_SETTINGS_MODULE: !Ref AppDjangoSettingsModule
          DB_HOST: !Ref AppDBHost
          DB_PASSWORD: !Ref AppDBPassword
          SENTRY_DSN: !Ref AppSentryDsn
      Events:
        ImportPeople:
          Type: Schedule # More info about API Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: import-recent-people
            Description: Update people from the last 5 minutes
            Input: '{"command": "import_people", "args": ["--recent"]}'
        ImportBallotsCurrent:
          Type: Schedule # More info about API Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: import-current-ballots
            Description: Update all ballots marked as current
            Input: '{"command": "import_ballots", "args": ["--current"]}'
        ImportBallotsFull:
          Type: Schedule # More info about API Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Properties:
            Schedule: rate(1 day)
            Name: import-ballots
            Description: Run a full import of ballots
            Input: '{"command": "import_ballots"}'
        ImportParties:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: import-parties
            Description: Import parties
            Input: '{"command": "import_parties"}'
        ImportVotesCast:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: import-votes-cast
            Description: Import votes cast from given date
            Input: '{"command": "import_votes_cast", "args": ["--since=2021-05-05"]}'
        ImportReferendums:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: import-referendums
            Description: Update Referendums from google sheet
            Input: '{"command": "import_referendums"}'


Outputs:
  WCIVFControllerFunctionArn:
    Description: "WCIVF Controller Lambda Function ARN"
    Value: !GetAtt WCIVFControllerFunction.Arn
