version = 0.1
[development]
[development.deploy]
[development.deploy.parameters]
stack_name = "WCIVFControllerApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bpwbpsluzkgd"
s3_prefix = "WCIVFController"
region = "eu-west-2"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
force_upload = true
