# Generated by Django 4.2.20 on 2025-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0049_personredirect"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personredirect",
            options={"get_latest_by": "ynr_created"},
        ),
        migrations.AddField(
            model_name="personredirect",
            name="ynr_created",
            field=models.DateTimeField(default="2010-01-01"),
            preserve_default=False,
        ),
    ]
