# Generated by Django 5.2.7 on 2025-10-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0050_alter_personredirect_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personredirect",
            name="old_person_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="personredirect",
            unique_together={("old_person_id", "new_person_id")},
        ),
    ]
