# Generated by Django 4.2.20 on 2025-07-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0044_fix_territory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="territory",
            field=models.CharField(
                choices=[
                    ("ENG", "England"),
                    ("NIR", "Northern Ireland"),
                    ("SCT", "Scotland"),
                    ("WLS", "Wales"),
                ],
                max_length=3,
                verbose_name="Territory",
            ),
        ),
    ]
