# Generated by Django 4.2.20 on 2025-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0045_alter_post_territory"),
    ]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="by_election_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEATH", "The elected member died"),
                    ("RESIGNATION", "The elected member resigned"),
                    (
                        "ELECTORAL_COURT",
                        "The election of the elected member was declared void by an election court",
                    ),
                    (
                        "FAILURE_TO_ACCEPT",
                        "The previous election winner did not sign a declaration of acceptance",
                    ),
                    (
                        "FAILURE_TO_ATTEND_MEETINGS",
                        "The elected member failed to attend meetings for six months",
                    ),
                    ("DISQUALIFICATION", "The elected member was disqualified"),
                    (
                        "LOSING_QUALIFICATION",
                        "The elected member no longer qualified as a registered elector",
                    ),
                    (
                        "RECALL_PETITION",
                        "The elected member was recalled by a successful recall petition",
                    ),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                    ("", "Neither a by-election nor a ballot"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
