# Generated by Django 4.2.20 on 2025-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0046_postelection_by_election_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postelection",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postelection",
            name="wikipedia_bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
