# Generated by Django 5.2.15 on 2026-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0052_alter_postelection_by_election_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="close_of_nominations",
            field=models.DateField(
                blank=True, help_text="Close of Nominations", null=True
            ),
        ),
        migrations.AddField(
            model_name="postelection",
            name="notice_of_election_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline to publish Notice of Election document",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postelection",
            name="postal_vote_application_deadline",
            field=models.DateField(
                blank=True,
                help_text="Postal vote application deadline",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postelection",
            name="registration_deadline",
            field=models.DateField(
                blank=True, help_text="Register to vote deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="postelection",
            name="sopn_publish_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline to publish SOPN document",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postelection",
            name="vac_application_deadline",
            field=models.DateField(
                blank=True, help_text="VAC application deadline", null=True
            ),
        ),
    ]
